### ISSUE TITLE
Fails to run on a project with git patches

### ISSUE THREAD

**Issue by arturoc** [cecton/cargo-new-deps#1]
I'm getting:

```
fatal: ref refs/remotes/origin/HEAD is not a symbolic ref
Error: could not get default branch
```

Not sure if it's related to using git patches though

**Comment by cecton** [comment]
Sorry for the late reply! [I got the notifications turned off for some reason.](https://twitter.com/CecileTonglet/status/1469965435160432640?s=20)

I don't know if it could be related to git patches... :thinking: One possible issue I can think of is that you actually have pushed a branch called `HEAD`. I saw that in the past, it is something wrong and possible to do unintentionally. That would make `origin/HEAD` not a symbolic ref but a branch instead.

Let me know if that helps

**Comment by cecton** [comment]
I had the issue today! Try running this: `git remote set-head origin --auto`

**Comment by arturoc** [comment]
Hadn't had a chance to test this until now but just tested it and it solves it. Thanks!

**Comment by cecton** [comment]
Great!
